config/routes.rb
Rails.application.routes.draw do
  resources :pins
  root 'pins#index'
  get 'home/about'
  get 'home/contact'
  get 'home/faq'

  get '/login' => 'sessions#new', as: :signin
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy', as: :destroy_user

  get '/signup' => 'users#new', as: :new_user
  post '/users' => 'users#create'


end

app/models/pin.rb
class Pin < ActiveRecord::Base
  belongs_to :user
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :pins
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def user_signed_in?
    @current_user.present?
  end
  helper_method :user_signed_in?

  def authorize
    redirect_to '/login' unless current_user
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  # before_action :authenticate_user!, except: [:index, :show]
  # before_action :correct_user, only: [:edit, :update, :destroy]
  before_filter :authorize

  respond_to :html

  def index
    @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 3)
  end


  def show
  end


  def new
    @pin = current_user.pins.build
  end


  def edit
  end


  def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save
      redirect_to @pin, notice: "Pin was successfully created"
    else
      render action: 'new'
    end
  end


  def update
      if @pin.update(pin_params)
        redirect_to @pin, notice: 'Pin was successfully updated.'
      else
        ender :edit
      end
  end


  def destroy
    @pin.destroy
      redirect_to pins_url, notice: 'Pin was successfully destroyed.'
  end


  private
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def pin_params
      params.require(:pin).permit(:description, :image, :name)
    end

    def correct_user
      @pin = current_user.pins.find_by(id:params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to '/'
    else
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to :root, notice: 'Account created successfully'
    else
      flash[:error] = 'An error occured!'
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
      <div class="container">

        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'Pinterested', root_path,  class:"navbar-brand"%>
        </div>


        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right navtextcolor">
            <li><%= link_to 'Home', root_path,  class:"navtextcolor"%></li>
            <li><%= link_to 'About', home_about_path, class:"navtextcolor"%></li>
            <li><%= link_to 'List Pins', pins_path, class:"navtextcolor"%></li>

            <% if user_signed_in? %>
              <li><%= link_to 'Edit Profile', edit_user_registration_path, class:"navtextcolor"%></li>
              <li><%= link_to 'Add Pin', new_pin_path, class:"navtextcolor"%></li>
              <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete, class:"navtextcolor"%></li>
            <% else %>
              <li><%= link_to 'Login', signin_path, class:"navtextcolor"%></li>
              <li><%= link_to 'Join', new_user_path, class:"navtextcolor"%></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

app/views/home/about.html.erb
<div class="jumbotron">
  <h1>About</h1>
    <p class="lead">It's a lot like Pinterest.</p>
</div>

app/views/home/contact.html.erb
<div class="jumbotron">
  <h1>Contact</h1>
    <p class="lead">We're friendly people.</p>
</div>

app/views/home/faq.html.erb
<div class="jumbotron">
  <h1>FAQ</h1>
    <p class="lead">All the questions.</p>
</div>

app/views/home/index.html.erb
<div class="jumbotron">
  <h1>Welcome To My App</h1>
  <p class="lead">It's Gonna Kick All Ass...</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinterested</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

</head>
<body>

<%= render 'home/header' %>

<div class="container">

  <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-info") %>
    <% end %>

    <% if current_user %>
      Signed in as <%= @current_user.name %> | <%= link_to "Logout", '/logout' %>
    <% else %>
      <%= link_to 'Login', '/login' %> | <%= link_to 'Signup', '/signup' %>
    <% end %>

    <%= yield %>

</div>
</body>
</html>

app/views/pins/_form.html.erb
<%= form_for @pin, html: {
    multipart: true } do |f| %>

  <div class="form-inputs">
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing Pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<div id="pins" class="transitions-enabled">
    <% @pins.each do |pin| %>
    <div class="box">
      <div class="panel panel-default">
      <%= link_to image_tag(pin.image.url(:medium)), pin %></br>
        <div class="panel-body">
        <%= pin.description %></br>
      </br><strong><%= pin.user.name if pin.user %></strong><br/>
        </div>
          <% if pin.user == current_user %>
          <div class="panel-footer">
            <%= link_to 'Edit', edit_pin_path(pin) %></br>
            <%= link_to 'Destroy', pin, method: :delete, data:
          { confirm: 'Are you sure?' } %>
        </div>
        <% end %>
      </div>
    </div>
    <% end %>
  </div>
  <div class="center">
  <%= will_paginate @pins, renderer: BootstrapPagination::Rails %>
</div>

app/views/pins/new.html.erb
<h1>New Pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<div class="row">
  <div class="col-md-offset-2 col-md-8">

  <div class="panel panel-default">
    <div class="panel-heading center"><%= image_tag @pin.image.url(:medium) %></div>
    <div class="panel-body">

      <%= @pin.description %><br/>
      <br/><%= pin.user.name %><br/>

      <% if @pin.user == current_user %>
        <%= link_to 'Edit', edit_pin_path(@pin) %> |
      <% end %>
        <%= link_to 'Back', pins_path %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h1>Signup!</h1>

<%= form_for :user, url: '/users' do |f| %>

  Name: <%= f.text_field :name %>
  Email: <%= f.text_field :email %>
  Password: <%= f.password_field :password %>
  Password Confirmation: <%= f.password_field :password_confirmation %>
  <%= f.submit "Submit" %>

<% end %>